#!/bin/bash
# C.Orr 2020
rm xia2.sh
rm xia2_xds.phil

echo "Making the files for you. Type gen_xia2_xds -h for help"

while getopts a:s:u:r: option
	do
	case "${option}"
	in
		a) atom=${OPTARG};;
		s) space=${OPTARG};;
		u) unit=${OPTARG};;
		r) resolution=${OPTARG};;
		h) echo "Run using gen_xia2_xds -a scatteringatom -s spacegroupname -u 'unitcell constants (a b c al be ga') -r highrescutoff" >&2
	  exit 1
	esac
done

cat <<EOT >> xia2.sh
xia2 pipeline=3dii ./xia2_xds.phil /images/here
EOT

chmod +x xia2.sh

cat <<EOT >> xia2_xds.phil
general.check_image_files_readable=True
xds.z_min=0.0
xds.delphi=5.0
xds.delphi_small=30.0
xds.keep_outliers=False
xds.correct.refine=*DISTANCE *BEAM *AXIS *ORIENTATION *CELL *POSITION
xds.integrate.refine=*ORIENTATION *CELL *BEAM *DISTANCE AXIS *POSITION
xds.integrate.refine_final=*ORIENTATION *CELL BEAM *DISTANCE AXIS *POSITION
xds.integrate.fix_scale=False
xds.integrate.delphi=0.0
xds.integrate.reflecting_range=0.0
xds.integrate.reflecting_range_esd=0.0
xds.integrate.beam_divergence=0.0
xds.integrate.beam_divergence_esd=0.0
xds.integrate.reintegrate=True
xds.init.fix_scale=False
xds.index.refine=*ORIENTATION *CELL *BEAM *DISTANCE *AXIS *POSITION
xds.index.debug=OFF
xds.index.max_wedge_size=5
xds.colspot.minimum_pixels_per_spot=1
xds.xscale.min_isigma=3.0
xds.xscale.zero_dose=False
xds.merge2cbf.merge_n_images=2
xds.merge2cbf.moving_average=False
ccp4.reindex.program=pointless
ccp4.aimless.intensities=combine
ccp4.aimless.surface_tie=0.001
ccp4.aimless.surface_link=True
ccp4.aimless.rotation.spacing=5
ccp4.aimless.secondary.frame=crystal
ccp4.aimless.secondary.lmax=6
ccp4.truncate.program=ctruncate
xia2.settings.pipeline=3dii
xia2.settings.small_molecule=False
xia2.settings.small_molecule_bfactor=True
xia2.settings.failover=True
xia2.settings.multi_crystal=True
xia2.settings.interactive=False
xia2.settings.project=AUTOMATIC
xia2.settings.crystal=DEFAULT
xia2.settings.input.atom=$atom
xia2.settings.input.anomalous=Auto
xia2.settings.input.reverse_phi=False
xia2.settings.input.min_images=10
xia2.settings.input.tolerance.beam.wavelength=1e-06
xia2.settings.input.tolerance.beam.direction=1e-06
xia2.settings.input.tolerance.beam.polarization_normal=1e-06
xia2.settings.input.tolerance.beam.polarization_fraction=1e-06
xia2.settings.input.tolerance.detector.fast_axis=1e-06
xia2.settings.input.tolerance.detector.slow_axis=1e-06
xia2.settings.input.tolerance.detector.origin=0.05
xia2.settings.input.tolerance.goniometer.rotation_axis=1e-06
xia2.settings.input.tolerance.goniometer.fixed_rotation=1e-06
xia2.settings.input.tolerance.goniometer.setting_rotation=1e-06
xia2.settings.input.tolerance.scan.oscillation=0.01
xia2.settings.input.geometry.detector.panel.id=0
xia2.settings.input.geometry.goniometer.invert_rotation_axis=False
xia2.settings.input.geometry.scan.extrapolate_scan=False
xia2.settings.input.geometry.convert_stills_to_sweeps=False
xia2.settings.input.geometry.convert_sweeps_to_stills=False
xia2.settings.input.format.dynamic_shadowing=Auto
xia2.settings.input.format.multi_panel=False
xia2.settings.sweep.exclude=False
xia2.settings.scale.directory=Auto
xia2.settings.scale.free_fraction=0.05
xia2.settings.scale.model=*decay *modulation *absorption partiality
xia2.settings.scale.scales=rotation
xia2.settings.scale.two_theta_refine=True
xia2.settings.space_group=$space
xia2.settings.unit_cell=$unit
xia2.settings.resolution.keep_all_reflections=Auto
xia2.settings.resolution.d_max=1000.0
xia2.settings.resolution.d_min=$resolution
xia2.settings.resolution.cc_ref=0.1
xia2.settings.resolution.cc_half=0.3
xia2.settings.resolution.cc_half_method=half_dataset
xia2.settings.resolution.cc_half_significance_level=0.1
xia2.settings.resolution.cc_half_fit=tanh
xia2.settings.resolution.isigma=0.25
xia2.settings.resolution.misigma=1.0
xia2.settings.resolution.nbins=100
xia2.settings.resolution.binning_method=counting_sorted
xia2.settings.resolution.anomalous=False
xia2.settings.unify_setting=False
xia2.settings.trust_beam_centre=False
xia2.settings.wavelength_tolerance=5e-05
xia2.settings.read_all_image_headers=True
xia2.settings.show_template=False
xia2.settings.xds_check_cell_deviation=False
xia2.settings.use_brehm_diederichs=False
xia2.settings.integration.profile_fitting=True
xia2.settings.integration.exclude_ice_regions=False
xia2.settings.developmental.use_dials_spotfinder=False
xia2.settings.developmental.pointless_tolerance=0.0
xia2.settings.multi_sweep_indexing=Auto
xia2.settings.remove_blanks=False
xia2.settings.integrate_p1=False
xia2.settings.reintegrate_correct_lattice=True
xia2.settings.lattice_rejection=True
xia2.settings.lattice_rejection_threshold=1.5
xia2.settings.merging_statistics.source=cctbx
xia2.settings.merging_statistics.n_bins=20
xia2.settings.merging_statistics.use_internal_variance=False
xia2.settings.merging_statistics.eliminate_sys_absent=False
xia2.settings.verbose=False
xia2.settings.multiprocessing.mode=serial
xia2.settings.multiprocessing.nproc=20
xia2.settings.multiprocessing.type=simple
xia2.settings.report.resolution_bins=20
xia2.settings.report.anomalous=False
xia2.settings.report.use_internal_variance=False
xia2.settings.report.eliminate_sys_absent=False
xia2.settings.report.range.width=1.0
xia2.settings.report.cc_half_significance_level=0.01
xia2.settings.report.cc_half_method=half_dataset
xia2.settings.report.dose.remove_gaps=True
xia2.settings.report.xtriage_analysis=True
xia2.settings.report.include_radiation_damage=True
xia2.settings.report.include_probability_plots=False
xia2.settings.symmetry.program=pointless
EOT
